[package]
name = "gateway-proxy"
version = "0.1.0"
edition = "2022"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
base64 = "0.13"
flate2 = { version = "1.0", default-features = false }
futures-util = { version = "0.3", default-features = false }
halfbrown = { version = "0.1", features = ["serde"] }
hyper = { version = "0.14", default-features = false, features = [
    "server",
    "http1",
    "http2"
] }
itoa = "1.0"
libc = { version = "0.2", default-features = false }
metrics = { version = "0.19", default-features = false }
metrics-exporter-prometheus = { version = "0.10", default-features = false }
mimalloc = { version = "0.1", default-features = false, features = [
    "override"
] }
rand = "0.8"
ring = { version = "0.16", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", default-features = false, features = ["std"], optional = true }
simd-json = { version = "0.6", default-features = false, features = [
    "serde_impl"
], optional = true }
tokio-tungstenite = { version = "0.17", default-features = false }
tokio = { version = "1", default-features = false, features = [
    "rt-multi-thread"
] }
tracing = { version = "0.1", default-features = false, features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "fmt",
    "std"
] }
twilight-cache-inmemory = { git = "https://github.com/Gelbpunkt/twilight.git", branch = "custom-new", default-features = false }
twilight-gateway = { git = "https://github.com/Gelbpunkt/twilight.git", branch = "custom-new", default-features = false, features = [
    "rustls-webpki-roots",
] }
twilight-gateway-queue = { git = "https://github.com/Gelbpunkt/twilight.git", branch = "custom-new", default-features = false, features = [
    "rustls-webpki-roots",
] }
twilight-http = { git = "https://github.com/Gelbpunkt/twilight.git", branch = "custom-new", default-features = false, features = [
    "rustls-webpki-roots",
] }
twilight-model = { git = "https://github.com/Gelbpunkt/twilight.git", branch = "custom-new" }

[patch.crates-io]
metrics = { git = "https://github.com/metrics-rs/metrics.git", branch = "dependabot/cargo/parking_lot-0.12" }
metrics-exporter-prometheus = { git = "https://github.com/metrics-rs/metrics.git", branch = "dependabot/cargo/parking_lot-0.12" }

[features]
default = ["simd"]
simd = ["flate2/zlib-ng", "simd-json", "twilight-gateway/zlib-simd", "twilight-gateway/simd-json", "twilight-http/simd-json"]
no-simd = ["flate2/zlib", "serde_json"]

[profile.release]
codegen-units = 1
debug = false
incremental = false
lto = true
opt-level = 3
panic = "abort"
debug-assertions = false
